### ISSUE TITLE
Should we import the Marl sentiment also?

### ISSUE THREAD

**Issue by dpriskorn** [dpriskorn/LexDanNet#10]
I wonder if we have a good property for importing "sentiment" on lexemes or senses?
They appear in DanNet see e.g. https://wordnet.dk/dannet/data/word-11003567
and seem like a nice thing to have in Wikidata as well
They are using this namespace: http://www.gsi.upm.es/ontologies/marl/

**Comment by fnielsen** [comment]
It is from The Danish Sentiment Lexicon at
https://github.com/dsldk/danish-sentiment-lexicon/blob/main/2_headword_headword_polarity.csv

With the CC-BY-SA 4.0 license I do not think we can import it.

**Comment by fnielsen** [comment]
If we only use P1343, see https://ordia.toolforge.org/reference/Q123909217, then I think we are ok.

**Comment by dpriskorn** [comment]
I plan to create a new tool to help editors add sentiment to senses in the next Hackathon if I get a scholarship 😀

**Comment by fnielsen** [comment]
I suppose one could set up a Wikibase, e.g., at wikibase.cloud where collaborative annotation can occur, - and not just for sentiment - but other forms of annotations?
